### ISSUE TITLE
pytest_runtest_makereport crashes on test exceptions

### ISSUE THREAD

**Issue by avshalomt2** [shawnbrown/datatest#42]
If an exception is thrown within a test that uses the test_db_engine fixture, the pytest_runtest_makereport function crashes.
The reason is that it uses Node's deprecated get_marker function, instead of the new get_closest_marker function.
See details about this change in pytest here:
https://docs.pytest.org/en/latest/mark.html#updating-code

**Comment by shawnbrown** [comment]
I have to thank you twice for this--once for filing the issue and again for the patch.

The changes have been merged: d5c77f7652bbef62afccef5840493f877aac2404

**Comment by shawnbrown** [comment]
I have also addressed this in the plugin's development repository.

You can see the changes here: shawnbrown/pytest-datatest@70107a4

After I release a bug-fix version of the plugin, I will add it to main datatest repository.
